IN: "/Sid/snurk/mts/sim/data"
SPADES: "~/Projects/mts/assembler/"
QUAST: "python2 ~/opt/quast-3.2/metaquast.py"
BIN: "~/Projects/mts/assembler/build/release/bin"
SCRIPTS: "~/Projects/mts/assembler/src/projects/mts/scripts"
SOFT: "/home/snurk/soft/"
REF: "/Sid/snurk/mts/nielsen/ref.fasta"
K: 55
small_k: 21
MIN_CONTIG_LENGTH: 2000
