genome:
    /lustre/scratch115/realdata/mdt3/projects/graphs/yeast/erik/final_exp/segdup/david/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa

regions:
    original: /lustre/scratch115/realdata/mdt3/projects/graphs/yeast/erik/final_exp/segdup/david/ccs_vs_hg38/table8_all.bed
    slop15k: /lustre/scratch115/realdata/mdt3/projects/graphs/yeast/erik/final_exp/segdup/david/ccs_vs_hg38/table8_all.15kbWindow.merged.bed

reads:
    pacbio: /lustre/scratch115/realdata/mdt3/projects/graphs/yeast/erik/final_exp/segdup/david/reads.pacbio.fastq
    nanopore: /lustre/scratch115/realdata/mdt3/projects/graphs/yeast/erik/final_exp/segdup/david/reads.nanopore.fastq

#Paths to tools (minimap2, samtools and bedtools are assumed to be in PATH)
tools:
    paftest: /lustre/scratch115/realdata/mdt3/projects/graphs/yeast/erik/final_exp/segdup/david/WHdenovo/paftest
    bandage: /lustre/scratch115/realdata/mdt3/projects/graphs/yeast/erik/final_exp/segdup/david/bin/Bandage
    mc-mpc: /lustre/scratch115/realdata/mdt3/projects/graphs/yeast/erik/final_exp/segdup/david/bin/mc-mpc
    graphaligner: /nfs/users/nfs_s/sg20/anaconda3/bin/GraphAligner
