genome:
    .../assembly.fa

hg38:
    .../GCA_000001405.15_GRCh38_no_alt_analysis_set.fa

regions:
    original:
        t5.b5.d2: .../chm13.segdups.norepeat.bed
        sda: .../chm13.collapses.bed
    slop15k: .../chm13.segdups.norepeat.slop15k.bed

reads:
    pacbio: .../reads.pacbio.fastq
    nanopore: .../reads.nanopore.fastq

#Paths to tools (minimap2, samtools and bedtools are assumed to be in PATH)
tools:
    paftest: .../WHdenovo/paftest
    bandage: .../Bandage
    mc-mpc: .../mc-mpc
    graphaligner: .../GraphAligner
    quast: .../quast.py
    svim-asm: .../svim-asm

bacs:
    fasta: .../bacs.fa

segdups: .../ucsc.merged.10k.slop.segdups.bed
